version: '3.8'

services:
  web:
    build: ./app
    command: python check_db.py
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    environment:
      # .env 파일에서 변수를 읽어옵니다.
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      # 이전에 논의한 infra 폴더 구조 반영
      - ./infra/postgres/data:/var/lib/postgresql/data/
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      # .env 파일에서 변수를 읽어옵니다.
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

# 'infra/postgres/data'를 사용하므로 명명된 볼륨 정의는 필요 없습니다.